# Generated by Django 4.2.23 on 2025-10-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread_notifications_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
