{
 "title": "Nix Security Tracker",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(sql_delta,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total number of CVEs",
   "type": "stat",
   "description": "Total number of CVEs in the database",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_cves{sql_job=\"sectracker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of derivations",
   "type": "stat",
   "description": "Total number of derivations in the database",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_derivations{sql_job=\"sectracker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of Evaluations",
   "type": "stat",
   "description": "Total number of Evaluations in the database",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_evaluations{sql_job=\"sectracker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registered users",
   "type": "stat",
   "description": "Number of registered users in the database",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_users{sql_job=\"sectracker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last delta run",
   "type": "stat",
   "description": "How many hours ago the last delta ran",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - sql_delta{sql_job=\"sectracker\"}) / 3600",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Last matching run",
   "type": "stat",
   "description": "How many hours ago the last matching ran",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - sql_matching{sql_job=\"sectracker\"}) / 3600",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Host metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"web-security-tracker\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}