# Generated by Django 4.2.7 on 2023-12-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0006_alter_nixlicense_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nixlicense",
            name="full_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
