# Generated by Django 4.2.7 on 2023-12-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0007_alter_nixlicense_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nixmaintainer",
            name="github",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="nixmaintainer",
            name="github_id",
            field=models.IntegerField(null=True),
        ),
    ]
