# Generated by Django 4.2.7 on 2023-12-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0009_alter_nixmaintainer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nixlicense",
            name="url",
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="nixlicense",
            unique_together={("full_name", "short_name", "spdx_id", "url")},
        ),
    ]
