# Generated by Django 4.2.7 on 2023-12-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0010_alter_nixlicense_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nixlicense",
            name="url",
            field=models.URLField(null=True),
        ),
    ]
