# Generated by Django 4.2.7 on 2023-12-05 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0011_alter_nixlicense_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nixderivation",
            name="metadata",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derivation",
                to="shared.nixderivationmeta",
            ),
        ),
    ]
