# Generated by Django 4.2.7 on 2023-12-05 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0003_nixpkgsissue_id"),
        ("shared", "0014_alter_nixderivationmeta_description_and_more"),
    ]

    operations = []
