# Generated by Django 4.2.7 on 2023-12-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0015_merge_20231205_0706"),
    ]

    operations = [
        migrations.AddField(
            model_name="nixpkgsissue",
            name="derivations",
            field=models.ManyToManyField(to="shared.nixderivation"),
        ),
        migrations.RemoveField(
            model_name="nixpkgsissue",
            name="cve",
        ),
        migrations.AddField(
            model_name="nixderivationmeta",
            name="known_vulnerabilities",
            field=models.ManyToManyField(to="shared.container"),
        ),
    ]
