# Generated by Django 4.2.7 on 2023-12-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0021_merge_20231211_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nixmaintainer',
            name='github',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nixmaintainer',
            name='github_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='nixpkgsissue',
            name='derivations',
            field=models.ManyToManyField(related_name='issues', to='shared.nixderivation'),
        ),
    ]
