# Generated by Django 4.2.7 on 2023-12-11 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0022_nixchannel_head_sha1_commit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nixchannel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nixchannel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="nixevaluation",
            name="attempt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nixevaluation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nixevaluation",
            name="state",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "Completed"),
                    ("WAITING", "Waiting to be started"),
                    ("IN_PROGRESS", "In progress"),
                    ("CRASHED", "Crashed"),
                    ("FAILED", "Failed"),
                ],
                default="COMPLETED",
                max_length=11,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nixevaluation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
