# Generated by Django 4.2.7 on 2023-12-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0022_alter_nixmaintainer_github_and_more'),
        ('shared', '0022_nixchannel_head_sha1_commit_and_more'),
    ]

    operations = [
    ]
