# Generated by Django 4.2.7 on 2023-12-12 01:02

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0023_nixchannel_created_at_nixchannel_updated_at_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="nixchannel",
            trigger=pgtrigger.compiler.Trigger(
                name="pgpubsub_ae5b1",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare="DECLARE payload TEXT;",
                    func="\n            \n            payload := json_build_object(\n                'app', 'shared',\n                'model', 'NixChannel',\n                'old', row_to_json(OLD),\n                'new', row_to_json(NEW)\n              );\n        \n            \n            perform pg_notify('pgpubsub_ae5b1', payload);\n            RETURN NEW;\n        ",
                    hash="e4f38cbd82ee07621ae9d61e3a672c6d36a49aa4",
                    operation="INSERT",
                    pgid="pgtrigger_pgpubsub_ae5b1_eb186",
                    table="shared_nixchannel",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="nixderivation",
            trigger=pgtrigger.compiler.Trigger(
                name="pgpubsub_8990c",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare="DECLARE payload TEXT;",
                    func="\n            \n            payload := json_build_object(\n                'app', 'shared',\n                'model', 'NixDerivation',\n                'old', row_to_json(OLD),\n                'new', row_to_json(NEW)\n              );\n        \n            \n            perform pg_notify('pgpubsub_8990c', payload);\n            RETURN NEW;\n        ",
                    hash="706d837058e03053ca81d1250975651f45de4fc9",
                    operation="INSERT",
                    pgid="pgtrigger_pgpubsub_8990c_fc631",
                    table="shared_nixderivation",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="nixevaluation",
            trigger=pgtrigger.compiler.Trigger(
                name="pgpubsub_aa9f7",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare="DECLARE payload TEXT;",
                    func="\n            \n            payload := json_build_object(\n                'app', 'shared',\n                'model', 'NixEvaluation',\n                'old', row_to_json(OLD),\n                'new', row_to_json(NEW)\n              );\n        \n            \n            perform pg_notify('pgpubsub_aa9f7', payload);\n            RETURN NEW;\n        ",
                    hash="2b352a83715f828dbf92ea03712271db33505ff9",
                    operation="INSERT",
                    pgid="pgtrigger_pgpubsub_aa9f7_77b01",
                    table="shared_nixevaluation",
                    when="AFTER",
                ),
            ),
        ),
    ]
