# Generated by Django 4.2.7 on 2023-12-12 03:24

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0024_nixchannel_pgpubsub_ae5b1_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="nixderivation",
            name="pgpubsub_8990c",
        ),
    ]
