# Generated by Django 4.2.7 on 2024-06-19 18:09

from django.db import migrations

def insert_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    # Security team members get admin permissions (all permissions)
    Group.objects.create(name="security_team")
    # Nixpkgs committers get write permissions for all packages
    Group.objects.create(name="committers")
    # Maintainers get write permissions for packages they maintain
    Group.objects.create(name="maintainers")
    # Everyone else get read permissions for all packages
    Group.objects.create(name="readers")


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0025_socialuser'),
    ]

    operations = [
        migrations.RunPython(insert_groups),
    ]
