# Generated by Django 4.2.7 on 2023-12-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0025_remove_nixderivation_pgpubsub_8990c"),
    ]

    operations = [
        migrations.AddField(
            model_name="nixevaluation",
            name="elapsed",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
