# Generated by Django 4.2.7 on 2024-06-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0025_affectedproduct_search_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkageCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('UNTRIAGED', 'UNTRIAGED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='UNTRIAGED', max_length=9)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkage_candidate', to='shared.container')),
                ('derivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkage_candidate', to='shared.nixderivation')),
            ],
        ),
    ]
