# Generated by Django 4.2.7 on 2023-12-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0025_nixpkgsissuecvelog_nixpkgsissuederivationslog_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW log_nixpkgsissue AS
            WITH issuelogcontext AS (
                SELECT context.id AS context_id,
                    context.created_at AS timestamp,
                    (context.metadata->>'user')::bigint AS user_id,
                    'shared_nixpkgsissue' AS table,
                    issuelog.pgh_obj_id AS entry_id,
                    'status' AS field,
                    issuelog.pgh_label AS action,
                    issuelog.status AS value,
                    null::bigint AS value_id
                FROM pghistory_context context INNER JOIN
                    shared_nixpkgsissuelog issuelog
                    ON context.id = issuelog.pgh_context_id
            ), icvelogcontext AS (
                SELECT context.id AS context_id,
                    context.created_at AS timestamp,
                    (context.metadata->>'user')::bigint AS user_id,
                    'shared_nixpkgsissue' AS table,
                    icvelog.nixpkgsissue_id AS entry_id,
                    'cve' AS field,
                    icvelog.pgh_label AS action,
                    cve.cve_id AS value,
                    icvelog.cverecord_id AS value_id
                FROM pghistory_context context INNER JOIN
                    public.shared_nixpkgsissuecvelog icvelog
                    ON context.id = icvelog.pgh_context_id INNER JOIN
                    shared_cverecord cve
                    ON icvelog.cverecord_id = cve.id
            ), idrvlogcontext AS (
                SELECT context.id AS context_id,
                    context.created_at AS timestamp,
                    (context.metadata->>'user')::bigint AS user_id,
                    'shared_nixpkgsissue' AS table,
                    idrvlog.nixpkgsissue_id AS entry_id,
                    'derivations' AS field,
                    idrvlog.pgh_label AS action,
                    drv.attribute AS value,
                    idrvlog.nixderivation_id AS value_id
                FROM pghistory_context context INNER JOIN
                    shared_nixpkgsissuederivationslog idrvlog
                    ON context.id = idrvlog.pgh_context_id INNER JOIN
                    shared_nixderivation drv
                    ON idrvlog.nixderivation_id = drv.id
            ), issue_activity_log AS (
                SELECT * FROM issuelogcontext
                UNION ALL
                SELECT * FROM icvelogcontext
                UNION ALL
                SELECT * FROM idrvlogcontext
            ), issue_activity_log_grouped AS (
                SELECT context_id,
                    timestamp,
                    user_id,
                    l.table,
                    entry_id,
                    jsonb_agg(jsonb_build_object(
                            'field',    field,
                            'action',   action,
                            'value',    value,
                            'value_id', value_id
                    )) AS changes
                FROM issue_activity_log l
                GROUP BY context_id, timestamp, user_id, l.table, entry_id
                ORDER BY timestamp
            )
            SELECT row_number() OVER () as id, ialg.* FROM issue_activity_log_grouped ialg
            """,
            """
            DROP VIEW IF EXISTS log_nixpkgsissue;
            """
        ),
    ]
