# Generated by Django 4.2.7 on 2023-12-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0026_nixevaluation_elapsed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nixevaluation",
            name="elapsed",
            field=models.FloatField(null=True),
        ),
    ]
