# Generated by Django 4.2.7 on 2023-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0029_remove_nixderivationmeta_platforms_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nixstorepathoutput",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="nixstorepathoutput",
            name="store_path",
            field=models.CharField(max_length=255, unique=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name="nixstorepathoutput",
            name="output_name",
        ),
    ]
