# Generated by Django 4.2.7 on 2023-12-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0030_alter_nixstorepathoutput_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nixevaluation",
            name="failure_reason",
            field=models.TextField(null=True),
        ),
    ]
