# Generated by Django 4.2.16 on 2024-10-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0030_cverecord_pgpubsub_c1d4d'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEDerivationClusterProposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted')], default='pending', max_length=8)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivation_links_proposals', to='shared.cverecord')),
                ('derivations', models.ManyToManyField(related_name='cve_links_proposals', to='shared.nixderivation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
