# Generated by Django 4.2.7 on 2023-12-18 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0031_nixevaluation_failure_reason_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nixevaluation",
            unique_together={("channel", "commit_sha1")},
        ),
    ]
