# Generated by Django 4.2.7 on 2023-12-18 18:52

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0032_alter_nixmaintainer_github_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="nixevaluation",
            name="pgpubsub_aa9f7",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="nixevaluation",
            trigger=pgtrigger.compiler.Trigger(
                name="pgpubsub_aa9f7",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare="DECLARE payload TEXT;",
                    func="\n            \n            payload := json_build_object(\n                'app', 'shared',\n                'model', 'NixEvaluation',\n                'old', row_to_json(OLD),\n                'new', row_to_json(NEW)\n              );\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES ('pgpubsub_aa9f7', to_json(payload::text));\n        \n            perform pg_notify('pgpubsub_aa9f7', payload);\n            RETURN NEW;\n        ",
                    hash="25db610c183b644bb790893fdd3c4df4cbe1ccf3",
                    operation="INSERT",
                    pgid="pgtrigger_pgpubsub_aa9f7_77b01",
                    table="shared_nixevaluation",
                    when="AFTER",
                ),
            ),
        ),
    ]
