# Generated by Django 4.2.16 on 2024-10-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0037_auto_20241014_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvederivationclusterproposal',
            name='derivations',
        ),
    ]
