# Generated by Django 4.2.16 on 2024-11-20 15:28

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0042_cachedsuggestions'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='cvederivationclusterproposal',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_8c7ef', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload TEXT;', func="\n            \n            payload := json_build_object(\n                'app', 'shared',\n                'model', 'CVEDerivationClusterProposal',\n                'old', row_to_json(OLD),\n                'new', row_to_json(NEW)\n              );\n        \n            \n            perform pg_notify('pgpubsub_8c7ef', payload);\n            RETURN NEW;\n        ", hash='35525381e11a1feeacd43d696db6c6d298cd064b', operation='UPDATE', pgid='pgtrigger_pgpubsub_8c7ef_29d5d', table='shared_cvederivationclusterproposal', when='AFTER')),
        ),
    ]
