# Generated by Django 4.2.16 on 2024-11-20 17:19

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0043_cvederivationclusterproposal_pgpubsub_8c7ef'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='container',
            name='pgpubsub_eb512',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='cvederivationclusterproposal',
            name='pgpubsub_8c7ef',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='nixchannel',
            name='pgpubsub_ae5b1',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='nixevaluation',
            name='pgpubsub_aa9f7',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='container',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_eb512', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "shared", "model": "Container"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_eb512\', payload);\n        \n            perform pg_notify(\'pgpubsub_eb512\', payload::text);\n            RETURN NEW;\n        ', hash='0e06f7ab4735d4ee11cae90de17c708aedd99323', operation='INSERT', pgid='pgtrigger_pgpubsub_eb512_7c98b', table='shared_container', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cvederivationclusterproposal',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_8c7ef', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "shared", "model": "CVEDerivationClusterProposal"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            perform pg_notify(\'pgpubsub_8c7ef\', payload::text);\n            RETURN NEW;\n        ', hash='1db9e8d8f55044823bbfa5ceb1b3338be320cf1b', operation='INSERT', pgid='pgtrigger_pgpubsub_8c7ef_29d5d', table='shared_cvederivationclusterproposal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixchannel',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_ae5b1', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "shared", "model": "NixChannel"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            perform pg_notify(\'pgpubsub_ae5b1\', payload::text);\n            RETURN NEW;\n        ', hash='b86ad39601e1e6aa33011529e6a6c6d71fd03b38', operation='INSERT', pgid='pgtrigger_pgpubsub_ae5b1_eb186', table='shared_nixchannel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixevaluation',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_aa9f7', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "shared", "model": "NixEvaluation"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_aa9f7\', payload);\n        \n            perform pg_notify(\'pgpubsub_aa9f7\', payload::text);\n            RETURN NEW;\n        ', hash='acc73b097aac7d421e58d20d26a3bc94be72646d', operation='INSERT', pgid='pgtrigger_pgpubsub_aa9f7_77b01', table='shared_nixevaluation', when='AFTER')),
        ),
    ]
