# Generated by Django 4.2.16 on 2024-11-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0041_cvederivationclusterproposalstatusevent_and_more'),
        ('shared', '0044_remove_container_pgpubsub_eb512_and_more'),
    ]

    operations = [
    ]
