# Generated by Django 4.2.16 on 2024-12-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0045_merge_20241125_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedsuggestions',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cached', serialize=False, to='shared.cvederivationclusterproposal'),
        ),
        migrations.AlterField(
            model_name='cvederivationclusterproposal',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
