# Generated by Django 4.2.16 on 2025-05-06 09:14

from django.db import migrations

def remove_suffix(apps, schema_editor):
    NixDerivation = apps.get_model('shared', 'NixDerivation')
    for instance in NixDerivation.objects.all():
        if instance.attribute and instance.system:
            # Remove the suffix if it matches the system field
            suffix = f".{instance.system}"
            if instance.attribute.endswith(suffix):
                instance.attribute = instance.attribute.removesuffix(suffix)
                instance.save()

def reapply_suffix(apps, schema_editor):
    NixDerivation = apps.get_model('shared', 'NixDerivation')
    for instance in NixDerivation.objects.all():
        if instance.attribute and instance.system:
            # Reapply the suffix if it doesn't already exist
            suffix = f".{instance.system}"
            if not instance.attribute.endswith(suffix):
                instance.attribute = f"{instance.attribute}{suffix}"
                instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0047_alter_cvederivationclusterproposal_status_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_suffix, reverse_code=reapply_suffix),
    ]
