# Generated by Django 4.2.16 on 2025-05-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0049_maintainersedit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='maintainersedit',
            constraint=models.UniqueConstraint(fields=('suggestion', 'maintainer'), name='unique_maintainer_edit_per_suggestion'),
        ),
    ]
