# Generated by Django 4.2.16 on 2025-06-04 16:26

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0050_maintainersedit_unique_maintainer_edit_per_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedNixpkgsIssue',
            fields=[
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cached', serialize=False, to='shared.nixpkgsissue')),
                ('payload', models.JSONField()),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixpkgsissue',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_caec7', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "shared", "model": "NixpkgsIssue"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            perform pg_notify(\'pgpubsub_caec7\', payload::text);\n            RETURN NEW;\n        ', hash='b8b839ed888029e472745297581f1480190e019a', operation='INSERT', pgid='pgtrigger_pgpubsub_caec7_da493', table='shared_nixpkgsissue', when='AFTER')),
        ),
    ]
