# Generated by Django 4.2.16 on 2025-05-27 12:49

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0006_delete_aggregateevent'),
        ('shared', '0050_maintainersedit_unique_maintainer_edit_per_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainersEditEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('edit_type', models.CharField(choices=[('add', 'add'), ('remove', 'remove')], max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='maintainersedit',
            trigger=pgtrigger.compiler.Trigger(name='maintainers_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "shared_maintainerseditevent" ("edit_type", "id", "maintainer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "suggestion_id") VALUES (NEW."edit_type", NEW."id", NEW."maintainer_id", _pgh_attach_context(), NOW(), \'maintainers.add\', NEW."id", NEW."suggestion_id"); RETURN NULL;', hash='5b96eb578edc3275229e55b9e24756430a36b0ca', operation='INSERT', pgid='pgtrigger_maintainers_add_insert_5a0d0', table='shared_maintainersedit', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='maintainersedit',
            trigger=pgtrigger.compiler.Trigger(name='maintainers_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "shared_maintainerseditevent" ("edit_type", "id", "maintainer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "suggestion_id") VALUES (OLD."edit_type", OLD."id", OLD."maintainer_id", _pgh_attach_context(), NOW(), \'maintainers.remove\', OLD."id", OLD."suggestion_id"); RETURN NULL;', hash='0ac244ca29b06c756ec8d5b4e524ae5de526b551', operation='DELETE', pgid='pgtrigger_maintainers_remove_delete_91230', table='shared_maintainersedit', when='AFTER')),
        ),
        migrations.AddField(
            model_name='maintainerseditevent',
            name='maintainer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='shared.nixmaintainer'),
        ),
        migrations.AddField(
            model_name='maintainerseditevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='maintainerseditevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='shared.maintainersedit'),
        ),
        migrations.AddField(
            model_name='maintainerseditevent',
            name='suggestion',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='shared.cvederivationclusterproposal'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='maintainerseditevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='8f584fb7ac5ac5a3b1397a00019814f166243595', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_c53c8', table='shared_maintainerseditevent', when='BEFORE')),
        ),
    ]
