# Generated by Django 4.2.16 on 2025-05-27 14:08

from django.db import migrations
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0051_maintainerseditevent_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='maintainersedit',
            name='maintainers_add_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='maintainersedit',
            name='maintainers_remove_delete',
        ),
    ]
