# Generated by Django 4.2.6 on 2023-11-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpe",
            name="_product",
        ),
        migrations.RemoveField(
            model_name="module",
            name="_product",
        ),
        migrations.RemoveField(
            model_name="programfile",
            name="_product",
        ),
        migrations.RemoveField(
            model_name="programroutine",
            name="_product",
        ),
        migrations.AddField(
            model_name="affectedproduct",
            name="cpes",
            field=models.ManyToManyField(to="shared.cpe"),
        ),
        migrations.AddField(
            model_name="affectedproduct",
            name="modules",
            field=models.ManyToManyField(to="shared.module"),
        ),
        migrations.AddField(
            model_name="affectedproduct",
            name="program_files",
            field=models.ManyToManyField(to="shared.programfile"),
        ),
        migrations.AddField(
            model_name="affectedproduct",
            name="program_routines",
            field=models.ManyToManyField(to="shared.programroutine"),
        ),
    ]
