# Generated by Django 4.2.7 on 2023-12-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0005_alter_nixderivationmeta_homepage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nixlicense",
            name="short_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
