# Generated by Django 4.2.7 on 2023-12-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0012_alter_nixderivation_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nixderivationmeta",
            name="main_program",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
