# Generated by Django 4.2.7 on 2023-12-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0013_alter_nixderivationmeta_main_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nixderivationmeta",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="nixderivationmeta",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
