# Generated by Django 4.2.7 on 2023-12-09 20:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0016_cveingestion_cverecord_triaged"),
    ]

    operations = [
        migrations.AddField(
            model_name="nixderivationmeta",
            name="known_vulnerabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None
            ),
        ),
    ]
