# Generated by Django 4.2.7 on 2023-12-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0017_remove_nixpkgsissue_cve_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nixpkgsissue",
            name="derivations",
            field=models.ManyToManyField(to="shared.nixderivation"),
        ),
    ]
