# Generated by Django 4.2.7 on 2023-12-11 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0018_nixpkgsissue_derivations"),
        ("shared", "0020_alter_nixmaintainer_name"),
    ]
