# Generated by Django 4.2.7 on 2023-12-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0021_merge_20231211_1306"),
    ]

    operations = [
        migrations.AddField(
            model_name="nixchannel",
            name="head_sha1_commit",
            field=models.CharField(default="0000000000000000000", max_length=255),
            preserve_default=False,
        )
    ]
