# Generated by Django 4.2.7 on 2023-12-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0023_alter_nixstorepathoutput_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nixlicense',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='nixlicense',
            name='spdx_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='nixmaintainer',
            name='github',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='nixmaintainer',
            name='github_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
