# Generated by Django 4.2.7 on 2024-07-29 20:36

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0025_affectedproduct_search_vector_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nixderivation',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='shared_nixd_name_fd9eb7_btree'),
        ),
    ]
