# Generated by Django 4.2.7 on 2024-07-30 22:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0027_nixderivation_search_vector_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cverecord',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['cve_id'], name='shared_cver_cve_id_7c6dc8_btree'),
        ),
    ]
