# Generated by Django 4.2.7 on 2024-08-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0025_add_groups'),
        ('shared', '0028_cverecord_shared_cver_cve_id_7c6dc8_btree'),
    ]

    operations = [
    ]
