# Generated by Django 4.2.16 on 2024-10-04 12:59

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0029_merge_20240809_1013'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='cverecord',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_c1d4d', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload TEXT;', func="\n            \n            payload := json_build_object(\n                'app', 'shared',\n                'model', 'CveRecord',\n                'old', row_to_json(OLD),\n                'new', row_to_json(NEW)\n              );\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES ('pgpubsub_c1d4d', to_json(payload::text));\n        \n            perform pg_notify('pgpubsub_c1d4d', payload);\n            RETURN NEW;\n        ", hash='9cab88442484cdcec6fd043f1d389f922784e9a7', operation='INSERT', pgid='pgtrigger_pgpubsub_c1d4d_cf3b0', table='shared_cverecord', when='AFTER')),
        ),
    ]
