# Generated by Django 4.2.16 on 2024-10-04 13:15

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0031_cvederivationclusterproposals'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='cverecord',
            name='pgpubsub_c1d4d',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='container',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_eb512', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload TEXT;', func="\n            \n            payload := json_build_object(\n                'app', 'shared',\n                'model', 'Container',\n                'old', row_to_json(OLD),\n                'new', row_to_json(NEW)\n              );\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES ('pgpubsub_eb512', to_json(payload::text));\n        \n            perform pg_notify('pgpubsub_eb512', payload);\n            RETURN NEW;\n        ", hash='379c9f4af359a5ac7ec462e415970be6a26a3349', operation='INSERT', pgid='pgtrigger_pgpubsub_eb512_7c98b', table='shared_container', when='AFTER')),
        ),
    ]
