# Generated by Django 4.2.16 on 2024-10-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0032_remove_cverecord_pgpubsub_c1d4d_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CVEDerivationClusterProposals',
            new_name='CVEDerivationClusterProposal',
        ),
    ]
