# Generated by Django 4.2.16 on 2024-10-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0038_remove_cvederivationclusterproposal_derivations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvederivationclusterproposal',
            name='derivations',
            field=models.ManyToManyField(related_name='cve_links_proposals', through='shared.DerivationClusterProposalLink', to='shared.nixderivation'),
        ),
    ]
