# Generated by Django 4.2.16 on 2025-05-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0048_remove_attribute_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainersEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_type', models.CharField(choices=[('add', 'add'), ('remove', 'remove')], max_length=6)),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.nixmaintainer')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintainers_edits', to='shared.cvederivationclusterproposal')),
            ],
        ),
    ]
