# Generated by Django 4.2.23 on 2025-07-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0052_cachednixpkgsissue_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_type', models.CharField(choices=[('remove', 'remove')], max_length=6)),
                ('package_attribute', models.CharField(max_length=255)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_edits', to='shared.cvederivationclusterproposal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='packageedit',
            constraint=models.UniqueConstraint(fields=('suggestion', 'package_attribute'), name='unique_package_edit_per_suggestion'),
        ),
    ]
