# Generated by Django 4.2.23 on 2025-07-21 16:31

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0053_packageedit'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='nixchannel',
            name='pgpubsub_ae5b1',
        ),
        migrations.AlterField(
            model_name='cachednixpkgsissue',
            name='version',
            field=models.PositiveIntegerField(default=2),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixchannel',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_ae5b1', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "shared", "model": "NixChannel"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            perform pg_notify(\'pgpubsub_ae5b1\', payload::text);\n            RETURN NEW;\n        ', hash='ccb13db3b72e1309986b4c1b86fd68fd240f6c24', operation='UPDATE', pgid='pgtrigger_pgpubsub_ae5b1_eb186', table='shared_nixchannel', when='AFTER')),
        ),
    ]
