# Generated by Django 4.2.23 on 2025-07-21 16:43

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('shared', '0054_remove_nixchannel_pgpubsub_ae5b1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainersEditEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('edit_type', models.CharField(choices=[('add', 'add'), ('remove', 'remove')], max_length=6)),
                ('maintainer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='shared.nixmaintainer')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='shared.maintainersedit')),
                ('suggestion', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='shared.cvederivationclusterproposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='maintainerseditevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='8f584fb7ac5ac5a3b1397a00019814f166243595', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_c53c8', table='shared_maintainerseditevent', when='BEFORE')),
        ),
    ]
