# Generated by Django 4.2.24 on 2025-10-16 17:12

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0056_packageeditevent_packageeditevent_append_only'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nixderivation',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['attribute'], name='shared_nixd_attribu_5fcca7_btree'),
        ),
    ]
