name: checks
on:
  pull_request:
  push:
    branches: main
jobs:
  test:
    runs-on: nix
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix-build
