name: Database dumps
on:
  schedule:
    # At 04:00 every day.
    - cron: "* 4 * * *"
  # Let end users trigger a dump.
  workflow_dispatch:
# Don't do multiple database dumps at the same time!
concurrency:
  group: database-dump
  cancel-in-progress: true
jobs:
  dump-database-to-raito-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup WARP to gain IPv6
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v29
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Trust staging server public SSH host keys
        run: cat ./staging/staging_host_keys >> ~/.ssh/known_hosts
      - name: Dump database to S3
        run: nix-shell default.nix -A ci --run "dump-database"
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
