name: Deployments
on:
  # Run the deployment only once staging has been prepared.
  workflow_run:
    workflows: ["Dry activations"]
    branches: [main]
    types:
      - completed
  push:
    branches: main
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v29
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Trust staging server public SSH host keys
        run: cat ./infra/host_keys >> ~/.ssh/known_hosts
      - run: nix-shell default.nix -A ci --run deploy
