name: Deployments
on:
  # Run the deployment only once staging has been prepared.
  workflow_run:
    workflows: ["Trusted checks"]
    branches: [main]
    types:
      - completed
  push:
    branches: main
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Setup WARP to gain IPv6
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Trust staging server public SSH host keys
        run: cat ./staging/staging_host_keys >> ~/.ssh/known_hosts
      - run: ./staging/deploy.sh
